ci: Test with Go 1.24, Go 1.25 (#1508)
Test with Go 1.24, Go 1.25

similar to;
- #1409
- #1464

passed test: https://github.com/arukiidou/zap/pull/12

## note

### one slogtest added since Go 1.25, but still passed.

Go 1.25 will add another test case to testing/slogtest , but still
passed.

```
"a Handler should not output nested groups if there are no attributes"
```

### also upgrades golang.org/x/vuln to v1.1.4

bacause

https://github.com/arukiidou/zap/actions/runs/17769123099/job/50500165958#step:6:64

```
Run make vulncheck
cd tools && go install golang.org/x/vuln/cmd/govulncheck
go: downloading golang.org/x/vuln v1.1.3
go: downloading golang.org/x/telemetry v0.0.0-20240522233618-39ace7a40ae7
go: downloading golang.org/x/mod v0.19.0
go: downloading golang.org/x/tools v0.23.0
go: downloading golang.org/x/sync v0.7.0
# golang.org/x/tools/internal/tokeninternal
Error: ../../../../go/pkg/mod/golang.org/x/tools@v0.23.0/internal/tokeninternal/tokeninternal.go:64:9: invalid array length -delta * delta (constant -256 of type int64)
make: *** [Makefile:48: /home/runner/work/zap/zap//bin/govulncheck] Error 1
Error: Process completed with exit code 2.
```

---------

Signed-off-by: junya koyama <arukiidou@yahoo.co.jp>